#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'minimumLoss' function below.
#
# The function is expected to return an INTEGER.
# The function accepts LONG_INTEGER_ARRAY price as parameter.
#

def minimumLoss(price):
    dict1={}
    for i in range(len(price)):
        dict1[price[i]]=i
        
    arr=sorted(price)
    mini=100000000000
    for i in range(1,len(price)):
        if dict1[arr[i-1]]>dict1[arr[i]]:
            mini=min(mini,arr[i]-arr[i-1])
    return mini
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    price = list(map(int, input().rstrip().split()))

    result = minimumLoss(price)

    fptr.write(str(result) + '\n')

    fptr.close()
